### ISSUE TITLE
After authentication, the ui redirects to logout

### ISSUE THREAD

**Issue by landonreed** [conveyal/datatools-ui#316]
<a href="https://github.com/skinkie"><img src="https://avatars3.githubusercontent.com/u/502394?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [skinkie](https://github.com/skinkie)**
_Tuesday Jul 10, 2018 at 18:25 GMT_
_Originally opened as https://github.com/catalogueglobal/datatools-ui/issues/207_

----

I tried to setup catalogue. After I got Auth0 to work (this part needs to be better documented) I stumbled upon the UI logging me out every time after sign in. 

The error that pops up is: err = TypeError: Cannot read property 'datatools' of undefined at receiveTokenAndProfile (http://catalogue.openov.nl/dist/index.js:38117:69) at http://catalogue.openov.nl/dist/index.js:262636:35 at http://catalogue.openov.nl/dist/index.js:10675:24 at 

I did set up the datatools section in my Auth0 user in the app_metadata section. But the /userprofile does not contain this section, it does include things like nickname, picture (gravatar). There are quite some pages on Google about this issue, hence more people must have hit it.

How to move forward?

**Comment by landonreed** [comment]
<a href="https://github.com/joelhaasnoot"><img src="https://avatars2.githubusercontent.com/u/592662?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [joelhaasnoot](https://github.com/joelhaasnoot)**
_Tuesday Jul 10, 2018 at 19:12 GMT_

----

Auth0 has done some things over the last year or so to make itself OIDC compliant. That's nice, but they haven't been good about their documentation. The app_metadata feature no longer works well for new accounts, see https://community.auth0.com/t/how-can-i-make-app-metadata-available-in-userinfo-endpoint/6664 - it needs to be namespaced if added with a hack/rule.

**Comment by landonreed** [comment]
<a href="https://github.com/skinkie"><img src="https://avatars3.githubusercontent.com/u/502394?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [skinkie](https://github.com/skinkie)**
_Tuesday Jul 10, 2018 at 19:23 GMT_

----

https://github.com/catalogueglobal/datatools-ui/pull/72

**Comment by landonreed** [comment]
<a href="https://github.com/abyrd"><img src="https://avatars0.githubusercontent.com/u/112871?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [abyrd](https://github.com/abyrd)**
_Wednesday Jul 11, 2018 at 15:49 GMT_

----

I just talked to @landonreed about this - apparently Auth0 has changed significantly but Conveyal's Auth0 account still functions as it did before those changes, because it was created before the changes. 

We of course need to update this project to work with current-day Auth0 but hadn't confronted the problem yet. @landonreed is working on it.

**Comment by landonreed** [comment]
<a href="https://github.com/landonreed"><img src="https://avatars2.githubusercontent.com/u/2370911?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [landonreed](https://github.com/landonreed)**
_Tuesday Jul 24, 2018 at 20:26 GMT_

----

As I mentioned in #72, the proposed solution of using an Auth0 rule to make the `app_metadata` available in the user profile doesn't seem to play nicely with our existing production applications (i.e., it wipes out the `app_metadata` field that currently exists in the profile).  After attempting to implement a few different fixes without much success (partly due to the removal of the `tokeninfo` endpoint see catalogueglobal/datatools-server#102, it seems like a good bet is to entirely rethink how Auth0 is used in this application.

One approach we are considering is something that we have discussed previously internally: storing user permissions in a Users collection in the datatools-server MongoDB database. The authentication would still be handled by Auth0, but the user_id associated with the user would be used to lookup the permissions, which would be sent back to the client's browser to determine their access to the application.  I'll continue to update this issue as we make decisions and progress on this topic, but if other users have input on this approach, please do share it.

**Comment by landonreed** [comment]
<a href="https://github.com/ilarimikkonen"><img src="https://avatars1.githubusercontent.com/u/7221736?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ilarimikkonen](https://github.com/ilarimikkonen)**
_Tuesday Oct 09, 2018 at 15:27 GMT_

----

Hi,

are there any plans on how to proceed with enabling the Auth0 for new Auth0 accounts? I have experimented with this and corresponding serverside fix, and login works OK. Unfortunately now we are facing problems getting all other things (editor) working.

We'd be interested in further developing this, if it fits our needs. Unfortunately we are now stuck as we cannot verify if the editor has needed functionality

**Comment by landonreed** [comment]
<a href="https://github.com/landonreed"><img src="https://avatars2.githubusercontent.com/u/2370911?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [landonreed](https://github.com/landonreed)**
_Tuesday Oct 09, 2018 at 18:30 GMT_

----

Do the editor problems you're experiencing already have tickets documenting the issues? Or are the problems you're facing related to the Auth0 issue?

We are looking to resolve a number of outstanding PRs this week in both the UI and Server repositories.

**Comment by landonreed** [comment]
<a href="https://github.com/ilarimikkonen"><img src="https://avatars1.githubusercontent.com/u/7221736?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ilarimikkonen](https://github.com/ilarimikkonen)**
_Wednesday Oct 10, 2018 at 05:39 GMT_

----

I did not create issues. I was not sure that it would make sense to create issues when I've used a branches that are not merged to dev or master. I have a guess that they are somehow Auth0 related, but I'm not sure. Those problems I'm experiencing may have something to do with the changes I did to the code. 

I think the work that you have done is great. Would you guys be willing to have a quick call where I explain what we are trying to accomplish? I think that would help us resolve this quicker. I can make an issue, but there is the chance that my setup is somehow wrong and we spend a lot of time figuring that out

**Comment by landonreed** [comment]
<a href="https://github.com/xaverio"><img src="https://avatars3.githubusercontent.com/u/10834471?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [xaverio](https://github.com/xaverio)**
_Thursday Oct 18, 2018 at 17:51 GMT_

----

Same problem as issue's title
After authentication, the ui redirects to logout
