### ISSUE TITLE
Create version from snapshot failing for SamTrans

### ISSUE THREAD

**Issue by landonreed** [conveyal/datatools-ui#52]
```
java.lang.RuntimeException: Could not instantiate class
        at org.mapdb.SerializerPojo.deserializeUnknownHeader(SerializerPojo.java:483)
        at org.mapdb.SerializerBase.deserialize3(SerializerBase.java:1216)
        at org.mapdb.SerializerBase.deserialize(SerializerBase.java:1132)
        at org.mapdb.SerializerBase.deserialize(SerializerBase.java:867)
        at org.mapdb.SerializerPojo.deserialize(SerializerPojo.java:701)
        at org.mapdb.BTreeKeySerializer$BasicKeySerializer.deserialize(BTreeKeySerializer.java:89)
        at org.mapdb.BTreeMap$NodeSerializer.deserialize(BTreeMap.java:440)
        at org.mapdb.BTreeMap$NodeSerializer.deserialize(BTreeMap.java:288)
        at org.mapdb.Store.deserialize(Store.java:297)
        at org.mapdb.StoreDirect.get2(StoreDirect.java:486)
        at org.mapdb.StoreWAL.get2(StoreWAL.java:336)
        at org.mapdb.StoreWAL.get(StoreWAL.java:320)
        at org.mapdb.Caches$HashTable.get(Caches.java:246)
        at org.mapdb.EngineWrapper.get(EngineWrapper.java:58)
        at org.mapdb.TxEngine.get(TxEngine.java:192)
        at org.mapdb.TxEngine$Tx.getNoLock(TxEngine.java:427)
        at org.mapdb.TxEngine$Tx.get(TxEngine.java:402)
        at org.mapdb.EngineWrapper.get(EngineWrapper.java:58)
        at org.mapdb.TxEngine.get(TxEngine.java:192)
        at org.mapdb.BTreeMap.<init>(BTreeMap.java:541)
        at org.mapdb.DB.getTreeMap(DB.java:805)
        at org.mapdb.DB$BTreeMapMaker.makeOrGet(DB.java:667)
        at com.conveyal.datatools.editor.datastore.DatabaseTx.getMap(DatabaseTx.java:35)
        at com.conveyal.datatools.editor.datastore.FeedTx.buildSecondaryIndices(FeedTx.java:171)
        at com.conveyal.datatools.editor.datastore.FeedTx.<init>(FeedTx.java:112)
        at com.conveyal.datatools.editor.datastore.FeedTx.<init>(FeedTx.java:94)
        at com.conveyal.datatools.editor.datastore.VersionedDataStore.getFeedTx(VersionedDataStore.java:57)
        at com.conveyal.datatools.editor.jobs.ProcessGtfsSnapshotExport.run(ProcessGtfsSnapshotExport.java:81)
        at com.conveyal.datatools.editor.controllers.api.SnapshotController.writeSnapshotAsGtfs(SnapshotController.java:255)
        at com.conveyal.datatools.editor.controllers.api.SnapshotController.writeSnapshotAsGtfs(SnapshotController.java:269)
        at com.conveyal.datatools.manager.jobs.CreateFeedVersionFromSnapshotJob.run(CreateFeedVersionFromSnapshotJob.java:41)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
        at java.util.concurrent.CopyOnWriteArrayList.get(CopyOnWriteArrayList.java:387)
        at java.util.concurrent.CopyOnWriteArrayList.get(CopyOnWriteArrayList.java:396)
        at org.mapdb.SerializerPojo.deserializeUnknownHeader(SerializerPojo.java:450)
        ... 31 more
22:26:38.299 [Thread-11] ERROR c.c.d.m.j.CreateFeedVersionFromSnapshotJob - Unable to create temp file for snapshot
```

**Comment by trevorgerhardt** [comment]
@landonreed should this be in [conveyal/datatools-server](/conveyal/datatools-server)?

**Comment by landonreed** [comment]
Yes, it should. Moving over.
