### ISSUE TITLE
Cannot create a project

### ISSUE THREAD

**Issue by landonreed** [conveyal/datatools-ui#62]
_From @landonreed on June 12, 2017 14:23_

The [issue in catalugue_ui](https://github.com/catalogueglobal/catalogue_ui/issues/1) should be in this repo I think, @zbouziane.  6aa6d700c98623aab5dbcf928eb03862529d796f fixes this.

_Copied from original issue: catalogueglobal/datatools-ui#9_

**Comment by landonreed** [comment]
_From @zbouziane on June 13, 2017 9:16_

Right. Apologies!

**Comment by landonreed** [comment]
_From @zbouziane on June 13, 2017 9:19_

Re:
```
index.js:708 Uncaught TypeError: Cannot read property 'organizationId' of undefined
    at Object.a._onChangeName [as onChange] (https://cataloguedev.s3.amazonaws.com/dist/index.js:708:1826)
    at a.save (https://cataloguedev.s3.amazonaws.com/dist/index.js:141:1622)
    at Object.invokeGuardedCallback (https://cataloguedev.s3.amazonaws.com/dist/index.js:12938:56)
    at executeDispatch (https://cataloguedev.s3.amazonaws.com/dist/index.js:12842:427)
    at Object.executeDispatchesInOrder (https://cataloguedev.s3.amazonaws.com/dist/index.js:12842:679)
    at executeDispatchesAndRelease (https://cataloguedev.s3.amazonaws.com/dist/index.js:12836:842)
    at executeDispatchesAndReleaseTopLevel (https://cataloguedev.s3.amazonaws.com/dist/index.js:12836:1063)
    at Array.forEach (native)
    at forEachAccumulated (https://cataloguedev.s3.amazonaws.com/dist/index.js:13085:68)
    at Object.processEventQueue (https://cataloguedev.s3.amazonaws.com/dist/index.js:12836:2584)
```
Caused by:
```
_onChangeName = (name) => {
    const {project, projectNameChanged, saveProject} = this.props
    const proj = {name}
    // TODO: move this logic into action                                                                                                                                     
    if (project.organizationId) proj.organizationId = project.organizationId
    if (project.isCreating) saveProject(proj)
    else projectNameChanged(project, name)
  }
```
in ProjectsList.js

**Comment by landonreed** [comment]
@zbouziane, I believe this should be fixed with the commit mentioned above, unless I'm missing something.
